dynamic_form/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('survey/', views.SurveyListView.as_view(), name='survey_list'),
    path('create/', views.CreateSurveyView.as_view(), name='survey_create'),
    path('survey/<int:survey_id>/', views.SurveyDetailView.as_view(), name='survey_detail'),
    path('survey/<int:survey_id>/edit/', views.SurveyEditView.as_view(), name="survey_edit"),
    path('survey/<int:survey_id>/response/', views.RespondView.as_view(), name="survey_respond"),
    path('survey/<int:survey_id>/response/<int:response_id>/', views.RespondView.as_view(), name="response"),
]

dynamic_form/dynamic_form/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

dynamic_form/app/models.py
from django.db import models
from django.contrib.auth.models import User
from dynamic_forms.models import FormField, ResponseField
from django.shortcuts import reverse
# from django.contrib.postgres.fields import JSONField

# Create your models here.


class Survey(models.Model):
    """
    This model handles from creation using FormField from django dynamic forms
    """
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='user')
    form_title = models.CharField(max_length=64)
    description = models.TextField(blank=True, null=True)
    form = FormField()  # this guy here does the heavy lifting

    class Meta:
        verbose_name = 'survey'
        verbose_name_plural = 'surveys'
        ordering = ['form_title']

    def __str__(self):
        return self.form_title

    def get_absolute_url(self):
        return reverse('app:survey_detail', kwargs={'survey_id': self.pk})


class SurveyResponse(models.Model):
    """
        This model allows the storage of responses to forms created by the survey model.
    """
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    response = ResponseField()

dynamic_form/app/views.py
# from django.shortcuts import render, get_object_or_404, redirect
from .models import Survey, SurveyResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import (ListView, DetailView)
from django.views.generic.edit import (CreateView, UpdateView)
from dynamic_forms.views import DynamicFormMixin
# Create your views here.


class SurveyListView(ListView):
    """
    Creates the survey list view which doubles as the home page.
    A list of all survey forms
    """
    model = Survey

    def get_queryset(self):
        return Survey.objects.all()


class SurveyDetailView(DetailView):
    """
    Renders a detailed view of a selected survey and all responses to survey if any exist
    """
    model = Survey
    pk_url_kwarg = "survey_id"


class CreateSurveyView(LoginRequiredMixin, CreateView):
    """
    Create a new survey form using the django dynamic form
    """
    login_url = '/login/'
    model = Survey
    fields = ['form_title', 'description', 'form']
    template_name = "app/survey_form.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('app:survey_detail', kwargs={"survey_id": self.object.pk})


class SurveyEditView(UpdateView):
    """
    Edit an existing survey
    """
    model = Survey
    fields = '__all__'
    pk_url_kwarg = "survey_id"

    def get_success_url(self):
        return reverse('app:survey_detail', kwargs={"survey_id": self.object.pk})


class RespondView(DynamicFormMixin, CreateView):
    """
    this view allows end users to respond ie fill dynamically generated forms
    """
    model = SurveyResponse
    fields = ['response']
    template_name = "app/respond.html"

    form_model = Survey
    form_pk_url_kwarg = "survey_id"
    response_form_fk_field = "survey"
    response_field = "response"

    def get_success_url(self):
        return reverse('app:survey_detail', kwargs={"survey_id": self.form_instance.pk})

dynamic_form/app/templates/app/base.html
<!DOCTYPE html>
    {% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--BOOTSTRAP-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!--MEDIUM EDITOR-->
        <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <!--CUSTOM CSS-->
<!--        <link rel="stylesheet" href='{% static "css/blog.css"%}'>-->
    <!--FONTS-->
        <link href="https://fonts.googleapis.com/css?family=Big+Shoulders+Text|Montserrat&display=swap" rel="stylesheet">
<!--        <script type="text/javascript" src="{% static 'js/blog.js'%}"></script>-->
        {% block head %}
        {% endblock %}

    </head>
    <body>
        <div class="container" id="main">
            <!--NAV BAR-->
            <nav class="navbar navbar-expand-lg navbar-light bg-primary techfont custom-navbar">
                <a class="navbar-brand bigbrand" href="{% url 'app:survey_list' %}">Survey Generator</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">

                        <li class="nav-item active">
                            <a class="nav-link" href="https://www.github.com/jayanwana">GitHub</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav my-2 my-lg-0">
                        {% if user.is_authenticated %}
                        <!--ONLY AUTH USER CAN VIEW-->
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'app:survey_create' %}">New Survey</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link">Welcome: {{ user.username }}</a>
                            </li>
                        {% else %}
                        <!--ELSE LOGIN-->
                            <li class="nav-item" style="float: right;">
                                <a class="nav-link" href="{% url 'login' %}">Login<span class="fa fa-user" aria-hidden="true"></span></a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            <!--CONTENT-->
            <div class="content container">
                <div class="row">
                    <div class="col-md-8">
                        <div class="blog_posts">
                            {% block body %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </body>
</html>

dynamic_form/app/templates/app/bs4_form.html
<!DOCTYPE html>
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
          {{ error }}
      {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
    <div class="form-group row">
        {{ field.label_tag }}

        {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
        {% else %}
            {% render_field field class="editable medium-editor-textarea" %}
        {% endif %}

        {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
{% endfor %}

dynamic_form/app/templates/app/respond.html
{% extends 'app/base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit" value="submit">Submit</button>
</form>
{% endblock %}

dynamic_form/app/templates/app/survey_detail.html
<!DOCTYPE html>
    {% extends "app/base.html" %}
    {% block head %}
<title>{{survey.title}}</title>
    {% endblock %}


    {% block body %}
        <h1>{{survey.form_title}}</h1>
            <p class="postcontent">{{ survey.description }}</p>
        <a href="{% url 'app:survey_respond' survey.pk %}">Respond To Survey</a>
        <hr>
        <h2>Responses</h2>
        {% for surveyresponse in object.surveyresponse_set.all %}
        <ul>
            {% for key, value in surveyresponse.response.items %}
            <li><strong>{{key}}: </strong> {{value}}</li>
            {% endfor %}
        </ul>
        <hr>
        {% endfor %}
    {% endblock %}

dynamic_form/app/templates/app/survey_edit.html
{% extends 'app/base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" value="submit">Submit</button>
</form>
{% endblock %}

dynamic_form/app/templates/app/survey_form.html
<!DOCTYPE html>

{% extends "app/base.html" %}

{% block head %}
    <title>New Survey</title>
{% endblock %}

{% block body %}
    <h1>New Survey</h1>
        <form class="post-form" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-primary">Save</button>
        </form>
{% endblock %}

dynamic_form/app/templates/app/survey_list.html
<!DOCTYPE html>
{% extends "app/base.html" %}

{% block head %}
    <title>Home</title>
{% endblock %}

{% block body %}
    <div class="centerstage loader">

        {% for survey in survey_list %}
        <div class="post">
            <h1><a href="{% url 'app:survey_detail' survey_id=survey.pk %}">{{survey.form_title}}</a></h1>
            <p>{{ survey.description }}</p>
        </div>
        <hr>
        {% endfor %}
    </div>
{% endblock %}